server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movie-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ebe1?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    create-sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd
    
eureka:
   instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
